package pet;

/**
 * Created by Cory on 23/05/2017.
 */
public enum PetType {
    ASTRONAUT, SHEEP, PIG, COW, SKELETON, ZOMBIE, ENDERMAN, WITHER_SKELETON, CHICKEN, BLAZE, CAVE_SPIDER, CHARGED_CREEPER, CREEPER, SPIDER, OCELOT, WITCH, RABBIT, WOLF;
}
